source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'SpartanExample' do
  pod 'Spartan', :path => '../'
end

target 'Tests' do
    pod 'Spartan', :path => '../'
end
